### ISSUE TITLE
Messages from the server don't contain client names

### ISSUE THREAD

**Issue by nponeccop** [5HT/n2o.hs#16]
`MSG` handler should take the user name from `entry` the same way as `N2O_DISCONNECT` handler and send `<b>user</b>: msg` HTML message to the client

[n2o.hs#L43-L52](https://github.com/nponeccop/n2o.hs/blob/master/src/n2o.hs#L43-L52)

**Comment by swamp-agr** [comment]
`<b>user</b>` htmlencoding fun detected.

**Comment by 5HT** [comment]
howo about `jse`  `hte` naming or `js_encode` `html_encode` preserving compatibilty with `n2o` ?
