### ISSUE TITLE
Remove jQuery legacy from chat sample

### ISSUE THREAD

**Issue by nponeccop** [5HT/n2o.hs#2]

**Comment by swamp-agr** [comment]
Need to refactor:
- client: `/sample/client.js`
- server: `/src/n2o.hs`.

Replacement of existing `$()` functions (DOM manipulation) with their ES6 analogs should be done.
Minimal set of functions:
- .show/.hide
- .append
- .text/.val/.html
- .ready
- .submit
- .animate (?)

**Comment by nponeccop** [comment]
#33 should be implemented first, as it's going to remove some of the code.

@5HT may provide a more detailed roadmap.

**Comment by swamp-agr** [comment]
OK. I will remove redundancy at first.

**Comment by nponeccop** [comment]
You should use the existing helpers if they exist, such as `qi()`

https://github.com/synrc/n2o/blob/d867186cd965ff4dfed8b8c6f291ef689f0a3e30/priv/n2o.js#L20

(our local copy of `n2o.js` should be the same, if it is not you should synchronize)

**Comment by 5HT** [comment]
OK lets start with implementing 3 functions to update DOM:
1. insert_bottom
2. insert_top
3. remove

insert_top:

```
    wf:wire(wf:f(
        "qi('~s').insertBefore("
        "(function(){var div = qn('~s'); div.innerHTML = '~s'; return div.firstChild; })(),"
        "qi('~s').firstChild);",
        [Target,Tag,Render,Target])),
    wf:wire(wf:render(Actions)).
```

insert_bottom:

```
    wf:wire(wf:f(
        "(function(){ var div = qn('~s'); div.innerHTML = '~s';"
                     "qi('~s').appendChild(div.firstChild); })();",
        [Tag,Render,Target])),
    wf:wire(wf:render(Actions)).
```

remove:

```
remove(Target) ->
    wf:wire("var x=qi('"++wf:to_list(Target)++"'); x && x.parentNode.removeChild(x);").
```

https://github.com/synrc/n2o/blob/master/src/wf.erl#L20-L49

We needn't more.

.text/.val is called `querySource` https://github.com/synrc/n2o/blob/master/priv/protocols/nitrogen.js#L23

**Comment by swamp-agr** [comment]
Ok. After implementation these helpers on server side I need to adopt them with `call` function. Otherwise, I will remove `log`, `alert` functions on client side and make direct JS call from server.

**Comment by swamp-agr** [comment]
Remove this redundant code below (it processed on client now w/o jQuery).

```
-- helper --

insertBottom :: T.Text -> T.Text -> T.Text -> T.Text
insertBottom tag val tgt =
  T.concat [ "(function(){ var div = qn('", tag
           , "'); div.innerHTML = '", val
           , "'; var t = qi('",  tgt
           , "'); t.appendChild(div); t.scrollTop = t.scrollHeight; })();"
           ]

insertTop :: T.Text -> T.Text -> T.Text -> T.Text
insertTop tag val tgt =
  T.concat [ "(function(){ var t = qi('", tgt
           , "'); t.insertBefore((function(){ var div = qn('", tag
           , "'); div.innerHTML = '", val
           , "'; return div; })(), t.firstChild); t.scrollTop = 0})()"
           ]

remove :: T.Text -> T.Text
remove tgt =
  T.concat [ "var x=qi('", tgt, "'); x && x.parentNode.removeChild(x);" ]
```
