### ISSUE TITLE
More general StaticWebServer

### ISSUE THREAD

**Issue by nponeccop** [5HT/n2o.hs#49]
Unlike `webfs` and `contrib/static-tiny`, `contrib/static-web-server` is not general-purpose but has few paths to the chat application hardcoded: 
- [StaticWebServer.hs#63](https://github.com/nponeccop/n2o.hs/blob/90f5bfec805f8a8c59c15363183990c17c4ab02a/contrib/static-web-server/StaticWebServer.hs#L63)
- [StaticWebServer.hs#35](https://github.com/nponeccop/n2o.hs/blob/90f5bfec805f8a8c59c15363183990c17c4ab02a/contrib/static-web-server/StaticWebServer.hs#L35)

**Comment by swamp-agr** [comment]
After generalization we've got:

```
$ ./contrib/static-web-server/dist/build/StaticWebServer/StaticWebServer

Info 0: Listening on localhost:8000
```

client.html could be found at: `http://localhost:8000/sample/client.html`
Is it OK?

**Comment by nponeccop** [comment]
Yes. It is what happens with webfsd and static-tiny. The latter works on Windows too.
