### ISSUE TITLE
Document our static webserver usage in README.md

### ISSUE THREAD

**Issue by nponeccop** [5HT/n2o.hs#5]
Now an external server is required for html/js/css

**Comment by nponeccop** [comment]
As it was decided in gitter we should test http://www.rejetto.com/hfs/?f=dl and mention it in README.md if it works. If it's not - test a Galois web server and/or `wai-app-static` on Windows.

**Comment by swamp-agr** [comment]
What test we should make for Galois http server?
Please rename `/contrib/static-web-server/README` to `/contrib/static-web-server/README.md`.
What changes should be added to README?

**Comment by nponeccop** [comment]
I meant benchmarks. At this point any benchmark of serving static files will do.

As for README, recomendations to use nginx in production and our web server in development should be added to the main Readme.

**Comment by nponeccop** [comment]
Partially documented in Windows version of instructions
