### ISSUE TITLE
Cyrillic encoding error

### ISSUE THREAD

**Issue by swamp-agr** [5HT/n2o.hs#8]
server/client OS: Windows 7 x64.

How to reproduce: 
1. run n2o.exe
2. run server with sample/client.html
3. connect as "user".
4. type "ыыы" (without quotes) and press Enter.

ER: "ыыы" on client side.
AR: 
- "KKK" on client-side
- [AtomTerm "MSG",AtomTerm "KKK"] as a server log.

**Comment by swamp-agr** [comment]
I think root cause in `bert.js`.

> "ф".charCodeAt(0)

1092

>  var a = atom('ф'), ori = encode(a), buf = new Uint8Array(new ArrayBuffer(ori.length))
>  for (var i = 0; i < buf.length; i++) { buf[i] =  ori.charCodeAt(i); console.log(ori.charCodeAt(i) + ' vs ' + buf[i]) }

131 vs 131
VM3621:2 100 vs 100
VM3621:2 0 vs 0
VM3621:2 1 vs 1
VM3621:2 1092 vs 68

As you can see 1092 was truncated to 68.

**Comment by swamp-agr** [comment]
Maybe there are some limitations in Uint8Array.

**Comment by swamp-agr** [comment]
Hah. It broken by definition of Uint8Array. 
How we should store chars with code > 256 in 8-bit array?
Or should we change the logic of en_\* methods (there are usage of obj.value.length found)?

**Comment by nponeccop** [comment]
There is an UTF-8 encoding/decoding library already in the tree. Perhaps we should use it. https://github.com/nponeccop/n2o.hs/blob/master/static/utf8.js

Note that the interface should still allow us to send both raw bytestreams and utf8-encoded strings, so it's better not to change it to be utf8-only. We should ask @5HT

**Comment by 5HT** [comment]
utf8.js purpose is to encode/decode BinaryTerm not AtomTerm, however it could be used and for AtomTerm. Unfortunately Erlang doesn't support UTF-8 Atoms.

**Comment by nponeccop** [comment]
We are going to use `BinaryTerm` then as text messages are semantically definitely not LISP atoms

**Comment by 5HT** [comment]
I'm about `AtomTerm text`:

```
handle state _entry [AtomTerm "MSG", AtomTerm text]
```

Just replace to BinaryTerm

**Comment by nponeccop** [comment]
Can't we just use ``BinaryTerm` there and preserve the semantics of atoms?

**Comment by swamp-agr** [comment]
After replacing `AtomTerm` to `BinaryTerm` in Tuple we had such log:

```
Text "PING"
PING
Binary "\131h\STXd\NUL\ENQLOGONd\NUL\SOHD"
"Decoding"
"Protocol violation 5"
"Parsed"
[AtomTerm "LOGON",AtomTerm "D"]
Protocol violation
Text "PING"
PING
```

N2O.hs:

```
receiveMessage connection = do
    let loop = receiveMessage connection
    message    <- WS.receiveDataMessage connection
    print message
    case message of
         WS.Binary x -> print "Decoding" >> case decode x of
            TupleTerm x@[_, BinaryTerm y] -> print "Decoded" >> return x
            TupleTerm x@[_, _] -> print "Protocol violation 5" >> return x
            _ -> print "haha" >> error "Protocol violation"

         WS.Text x
             | x == "PING" -> putStrLn "PING" >> loop
             | otherwise  -> do
                print x
                error "protocol violation 2"
```

n2o.hs:

```
handle state entry [AtomTerm "LOGON", BinaryTerm name]
```

`decode` from `Data.Binary` decodes wrong type. Need to investigate further.

**Comment by 5HT** [comment]
You should send `name` field using `bin` packer in the `client.js`:

```
 ws.send(enc(tuple(atom('LOGON'),bin($('#user').val()))))
```

https://github.com/nponeccop/n2o.hs/blob/master/sample/client.js#L78

**Comment by swamp-agr** [comment]
`bin` function and server modification for BinaryTerm support does not resolve the issue properly.

> BINARY=itoa(109)
> itol("ф".length, 4) = ""=itoa(01)
> "ф"=itoa(1092)

1092 again truncated to 68.

**Comment by nponeccop** [comment]
Cyrillic usernames aren't encoded correctly

**Comment by swamp-agr** [comment]
Travis did not start. #8 close.
